### ISSUE TITLE
hdlcc server isn't starting

### ISSUE THREAD

**Issue by abyszuk** [suoto/vim-hdl#33]
When starting vim I get following error:
`Error detected while processing function vimhdl#setup..<SNR>73_Pyeval:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/abyszuk/.vim/bundle/vim-hdl/python/vimhdl/vim_client.py", line 87, in startServer
    self._waitForServerSetup()
  File "/home/abyszuk/.vim/bundle/vim-hdl/python/vimhdl/vim_client.py", line 162, in _waitForServerSetup
    reply = request.sendRequest()
  File "/home/abyszuk/.vim/bundle/vim-hdl/python/vimhdl/base_requests.py", line 89, in sendRequest
    requests.packages.urllib3.exceptions.NewConnectionError) as exc:
AttributeError: 'module' object has no attribute 'NewConnectionError'
E858: Eval did not return a valid python object `

I use quite standard install of CentOs 7. Python version 3.3

**Comment by suoto** [comment]
Have you installed vim-hdl using a plugin manager? Plugin managers should in theory handle submodules, so vim-hdl can use versions known to be compatible. The requests module used is version 2.9.1.

Could you please try doing

```
  cd ~/.vim/bundle/vim-hdl
  git submodule update --init --recursive
```

And try again?

**Comment by abyszuk** [comment]
Aaaaah, right...
I forgot "git submodule update" while I was setting up vim-hdl on another PC.
I use Pathogen as a plugin manager.
